# riscv64imac 无浮点，避免 compiler_builtins ABI 冲突（与 hello_drv/rust_ffi 一致）

# 重编 core：Rust 源码对 riscv 等目标会为 compiler_builtins 启用 no-f16-f128，可减 f128 等体积
# 需先安装：rustup component add rust-src
[unstable]
build-std = ["core"]
